### ISSUE TITLE
support has_many in YAML sources

### ISSUE THREAD

**Issue by Nowaker** [zilkey/active_hash#94]
``` ruby
class Plans::IsoDistro < ActiveYaml::Base
  include ActiveHash::Associations
  has_many :iso_images, class_name: 'Plans::IsoImage'
end

class Plans::IsoImage < ActiveHash::Base
  include ActiveHash::Associations
  belongs_to :iso_distro, class_name: 'Plans::IsoDistro'
end
```

``` yaml
- id: 1
  code: arch
  name: Arch Linux
  iso_images:
    - path: archlinux.iso
      bit: 64
    - path: ubuntu.iso
      bit: 32
```

> `@isos.first`
> `=> #<Plans::IsoDistro:0x007f75b8962348 @attributes={:id=>1, :code=>"arch", :name=>"Arch Linux", :iso_images=>[{"path"=>"archlinux.iso", "bit"=>64}, {"path"=>"ubuntu.iso", "bit"=>32}]}>`
> `@isos.first.iso_images`
> `=> []`

This could understand nested structures and create `IsoImage` objects too, along with an appropriate relation.

**Comment by syguer** [comment]
I'll close this because of long time is passed. If you need this again, please reopen.
Thanks.

**Comment by Nowaker** [comment]
Non-collaborators can't reopen.

**Comment by syguer** [comment]
@Nowaker Oh, sorry. I've reopened!

**Comment by Justin-Maxwell** [comment]
FWIW - Not yet using ActiveHash, but probably will be by the end of today...

This would be very cool for something related to the use case that led me looking for a static activemodel solution. (Very limited number of records, data is effectively read-only, the column structure changes probably more often than the recordset)

In fact, we're already seeding config data into ActiveRecord for another part of the system via two-tier YAML much like OP presents, that might be easier to manage if in ActiveHash - in that case, there are two different sub-configuration-record types.

So as a newcomer, put this down as a vote for 'cool thing to add somewhere down the line maybe'

**Comment by Fibrasek** [comment]
This would be extremely helpful.

I'm trying a similar case, where I have two `ActiveYaml::Base` models with relations, example:

```ruby
class PermissionGroupTemplate < ActiveYaml::Base
  ...
  has_many :permission_templates
  ...
end
```

```ruby
class PermissionTemplate < ActiveYaml::Base
  ...
  belongs_to :permission_template_group
  ...
end
```
Hence those examples, an structure like this in the yaml files would be interesting:
```yaml
# permission_group_templates.yml
- id: 1
  permission_template_ids: [1]
```

```yaml
# permission_templates.yml
- id: 1
  permission_group_template_id: 1
```

idk if the current implementation could support something like that, but it would be useful
